version: '3'
services:
  wildfly:
    build:
      dockerfile: Dockerfile.dev
      context: ./wildfly
    environment:
      -
    volumes:
     - '${PWD}/jsfcihelloworld/target/jsfcihelloworld.war:/opt/jboss/wildfly/standalone/deployments/jsfcihelloworld.war:rw'
    ports:
     - '8080:8080'
     - '9990:9990'
     - '8000:8000'
    depends_on:
    - postgres
  postgres:
    image: 'postgres:10'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  