version: '3'
services:
  wildfly:
    build:
      dockerfile: Dockerfile.dcevm
      context: ./wildfly
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - PGHOST=${PG_HOST}
      - PGPORT=5432
      - PGDATABASE=${PG_DATABASE}
    volumes:
     - '${PWD}/target/jsfcihelloworld.war:/opt/jboss/wildfly/standalone/deployments/jsfcihelloworld.war:rw'
    ports:
     - '${WFY_HTTP_PORT}:8080'
     - '${WFY_ADMIN_PORT}:9990'
     - '${WFY_DEBUG_PORT}:8787'
    depends_on:
    - postgres
  postgres:
    image: 'postgres:10'
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    ports:
    - '${PG_PORT}:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5