FROM jboss/wildfly
ADD ./postgresql-42.2.0.jar /tmp/
ADD ./configure.and.run.wildfly.sh /tmp/
USER root
RUN chmod +x /tmp/configure.and.run.wildfly.sh
USER jboss
RUN /opt/jboss/wildfly/bin/add-user.sh admin admin --silent
CMD ["/tmp/configure.and.run.wildfly.sh"]