FROM jboss/wildfly
ENV PGHOST localhost
ENV PGPORT 5432
ENV PGDATABASE postgres
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ADD ./postgresql-42.2.0.jar /tmp/
ADD ./configure.and.run.wildfly.sh /tmp/
USER root
RUN chmod +x /tmp/configure.and.run.wildfly.sh
USER jboss
RUN /opt/jboss/wildfly/bin/add-user.sh admin admin --silent
CMD ["/tmp/configure.and.run.wildfly.sh"] ["${PGHOST}"] ["${PGPORT}"] ["${PGDATABASE}"] ["${POSTGRES_USER}"] ["${POSTGRES_PASSWORD}"]